const palette = {
    white:          '#ffffff',
    black:          '#000000',
    lightestGray:   '#cecccc',
    darkGray:       '#313131',
    darkerGray:     '#272727',
    base0:     '#839496',
    blue:      '#268bd2',
    greyBlue:  '#afbcbd',
    cyan:      '#2aa198',
    green:     '#859900',
};

export default {
    linkColor:          palette.blue,
    linkGradient:       'linear-gradient(135deg, rgba(5,153,252,1) 0%, rgba(42,32,196,1) 100%)',
    linkGradientActive: 'rgba(0,28,99,1)',
    linkHoverColor:     palette.cyan,
    activeLinkColor:    palette.blue,
    bgColor:            palette.white,
    bgColorRGB:         '',
    bgColor2:           palette.white,
    bgColor2RGB:        '255,255,255', 
    textColor:          palette.black,
    headerColor:        palette.black,
    tagColor:           palette.lightestGray,
    tagBgColor:         palette.darkerGray,
    siteTitleTextShadow: false,
    headerFont:         '"Comfortaa", sans-serif',
    primaryFont:         '"Open Sans", sans-serif',
}