const palette = {
    white:          '#ffffff',
    black:          '#000000',
    lightestGray:   '#cecccc',
    darkGray:       '#1d1d1d',
    darkGreyRGB:    '49,49,49',
    darkerGray:     '#0e0e0e',
    darkerGreyRGB:  '39,39,39',
    base02:         '#073642',
    yellow:         '#b58900',
    orange:         '#cb4b16',
    red:            '#dc322f',
    green:          '#5fdc2f',
    lightRed:       '#e67d7b',
    blue:           '#16669d',
    lightBlue:      '#00c3fd',
};

export default {
    linkColor:          palette.white,
    linkHoverColor:     palette.lightBlue,
    activeLinkColor:    palette.lightBlue,
    bgColor:            palette.darkGray,
    headerBgColor:      palette.white,
    bgColor2:           palette.darkerGray,
    bgColor2RGB:        palette.darkerGreyRGB,
    textColor:          palette.lightestGray,
    headerColor:        palette.white,
    tagColor:           palette.lightestGray,
    tagBgColor:         palette.darkerGray,
    navMenuBgColor:     palette.white,
    navMenuLinkColor:   palette.black,
    siteTitleShadow:    '1px 2px 5px #a2a2a2',
    headerFont:         '"Open Sans", sans-serif',
    primaryFont:         '"Open Sans", sans-serif',
}